modLoader="${mod_loader}"
loaderVersion = "${mod_loader_version_range}"
license = "${license}"
issueTrackerURL="${issue_tracker_url}"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile = "${logo_file}"
logoBlur = ${logo_blur}
displayURL ="${display_url}"
displayTest = "${display_test}"
authors = "${mod_author}"
description = '''${description}'''
${dependencies}
