[versions]
plugin_neoforge = "2.0.+"


minecraft = "1.21.1"
neoforge = "21.1.211"
parchmentmc = "2024.11.10"

jei = "19.25.0.322"
ae2 = "19.2.17"


[libraries]
jei = { module = "mezz.jei:jei-1.21.1-neoforge", version.ref = "jei" }
ae2 = { module = "org.appliedenergistics:appliedenergistics2", version.ref = "ae2" }


[plugins]
neoforge = { id = "net.neoforged.moddev", version.ref = "plugin_neoforge" }
