[versions]
plugin_moddev = "2.0.141"
plugin_modPublishPlugin = "1.1.0"


minecraft = "26.1.2"
neoforge = "26.1.2.41-beta"

jei = "29.5.0.28"
ae2 = "26.1.6-alpha"


[libraries]
jei = { module = "mezz.jei:jei-26.1.2-neoforge", version.ref = "jei" }
ae2 = { module = "org.appliedenergistics:appliedenergistics2", version.ref = "ae2" }


[plugins]
moddev = { id = "net.neoforged.moddev", version.ref = "plugin_moddev" }
modPublishPlugin = { id = "me.modmuss50.mod-publish-plugin", version.ref = "plugin_modPublishPlugin" }
